services:
  - type: web
    name: captcha-tls-app
    env: docker
    plan: free
    buildCommand: "docker build -t captcha-tls-app ."
    startCommand: "docker run -p 8080:8080 captcha-tls-app"
    autoDeploy: true
    region: us
    envVars:
      - key: PYTHONHTTPSVERIFY
        value: "1"
    timeoutSeconds: 300
    port: 8080
